version: '3'

services:
  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./backend:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  backend:
    build:
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/share/nginx/html
    ports:
      - "9000:9000"
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/app
    ports:
      - "3000:3000"
  mysqldb:
    image: mysql:8.0.29-oracle
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: image_to_text
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      - PMA_HOSTS=mysqldb
      - PMA_PORT=3306
      - PMA_USER=mysql
      - PMA_PASSWORD=123456
